# Terminal stuff
set -s default-terminal "screen-256color"
set -as terminal-overrides ",xterm*:Tc"
set -sg escape-time 10
set -gq allow-passthrough on
set -g detach-on-destroy off
set -g allow-rename on
set -g extended-keys on
set -g extended-keys-format csi-u

# Start from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Theme
set -g status-style 'bg=default fg=color3'

# Keybinds
bind -T copy-mode-vi v send -X begin-selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key / command-prompt -p "Prompt:" "new-window \"opencode run 'Answer this question in TLDR style: %%' 2>/dev/null | nvim -R -c 'set ft=markdown' -\""
bind-key ? command-prompt -p "Search:" "new-window 'w3m \"https://duckduckgo.com/?q=%%\"'"
